### PR TITLE
Add getSingleDocument

### PR DESCRIPTION
**Pull request by greatschism**
Hi Hans. Can you take a look at the function "getSingleDocument".

### CODE REVIEW

**Comment by hansemannn** [comment]
It seems like you mixed up some files, resulting in two PR's (this one and #4). Can you combine the changes in this branch please? The rest looks fine!

**Review by hansemannn — APPROVED** [review]

**Comment by hansemannn** [comment]
Thanks a lot! I'll release the new version immediately.

**Comment by hansemannn** [comment]
Wait, there is a compile error now. Things like "self.db" do not exist. Did you change something else locally? I will need to revert this, if the other changes are not provided, but I'll give you some time to update it :)

Screenshot 2022-09-27 at 12 14 28

**Comment by hansemannn** [comment]
Fixed it for you 🙌

**Comment by greatschism** [comment]
> Fixed it for you 🙌

Thank you. I need to learn objective-c.

**Pull request merged**
